"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# ------------------------------------------------------------
# Base directory
# ------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env (local development)
load_dotenv(BASE_DIR / ".env")


# ------------------------------------------------------------
# Security (development only!)
# ------------------------------------------------------------

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-v_r(-=c6)2@@o0o+5o==4sxf2z-4(4f^j0$4my!5jcniosjt*j"
)

DEBUG = True

ALLOWED_HOSTS = []


# ------------------------------------------------------------
# Applications
# ------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "core",
]


# ------------------------------------------------------------
# Middleware
# ------------------------------------------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ------------------------------------------------------------
# URLs / WSGI
# ------------------------------------------------------------

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"


# ------------------------------------------------------------
# Templates
# ------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ------------------------------------------------------------
# Database
# ------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ------------------------------------------------------------
# Authentication (EMAIL LOGIN)
# ------------------------------------------------------------

AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# ------------------------------------------------------------
# Langdock configuration
# ------------------------------------------------------------

LANGDOCK_API_KEY = os.getenv("LANGDOCK_API_KEY", "")
LANGDOCK_ASSISTANT_ID = os.getenv("LANGDOCK_ASSISTANT_ID", "")
LANGDOCK_ASSISTANT_URL = "https://api.langdock.com/assistant/v1/chat/completions"
LANGDOCK_TIMEOUT = int(os.getenv("LANGDOCK_TIMEOUT", "120"))


# ------------------------------------------------------------
# Password validation
# ------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------

LANGUAGE_CODE = "de-de"
TIME_ZONE = "Europe/Berlin"
USE_I18N = True
USE_TZ = True


# ------------------------------------------------------------
# Static files
# ------------------------------------------------------------

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# ------------------------------------------------------------
# Default primary key
# ------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
